# Generated by Django 5.1.1 on 2024-09-16 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(default='Credit Card', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='registration_number',
            field=models.CharField(default='UNKNOWN123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donations', to='user.ngo'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
