# Generated by Django 5.1.1 on 2024-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_donation_donation_date_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo',
            name='verification_docs',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
