# Generated by Django 5.1.1 on 2024-09-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_ngo_email_ngo_verification_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charity_donations', to='user.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequestView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_name', models.CharField(max_length=255)),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharitySystem.donationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ngo')),
            ],
        ),
    ]
